### ISSUE TITLE
Sprache kann nicht erkannt werden

### ISSUE THREAD

**Issue by M1dn8** [rmbinder/Kategoriereport#28]
Hallo und vielen Dank für deine Arbeit.

Nach dem Update auf die neuste Version von Admidio habe ich nun auch dein Modul mit eingebunden und leider wird die Sprache nicht richtig aufgelöst, sodass ich überall die kryptischen #PLG_KATEGORIEREPORT_PLUGIN_NAME# usw. sehe.
Auch eine Umbennung der de.xml und de-DE.xml führte zu keinem Erfolg.

Ich hoffe du kannst mir helfen!

Beste Grüße

**Comment by rmbinder** [comment]
Hallo,
dieser Fehler tritt immer wieder mal auf. Lösche mal den Cache Deines Browsers, das hilft normalerweise.
(Wenn du als Sprache Deutsch (du) eingestellt hast, brauchst du die de.xml, bei Deutsch (Sie) brauchst du die de-DE.xml)
Viele Grüße
Rainer

**Comment by M1dn8** [comment]
Hallo Rainer,

danke für deine schnelle Antwort!
Das hat das Problem vorerst behoben! 
Vielen Dank

Beste Grüße
