### ISSUE TITLE
Export und Filter

### ISSUE THREAD

**Issue by M1dn8** [rmbinder/Kategoriereport#29]
Guten Morgen Rainer,

ein weiterer Fehler ist mir aufgefallen mit der Hoffnung du kannst Ihn ähnlich schnell beheben :)

Wenn ich im Kategoriereport bin und die Checkbox "Export und Filter" aktiviere dann bleibt das "Filter" Feld ohne Funktion.

Wäre klasse wenn du dafür eine Lösung finden würdest!

Beste Grüße

**Comment by rmbinder** [comment]
Das Feld "Filter" benötigt einen "Return".

**Comment by M1dn8** [comment]
Guten Morgen Rainer,

kennst du das bekanntliche Brett vorm Kopf ;)

Vielen Dank. Natürlich funktioniert die Funktion wie sie soll, wenn man dann ein "Return" macht!

Beste Grüße
