### ISSUE TITLE
Kategoriereport doesn't find its ui messages

### ISSUE THREAD

**Issue by luebbe** [rmbinder/Kategoriereport#30]
Running on Admidio 4.1 all UI strings in Kategoriereport look like `#PLG_KATEGORIEREPORT_...#`

![grafik](https://user-images.githubusercontent.com/3872576/141681264-f5cb2458-33c1-48f8-bd09-483924609fa0.png)

**Comment by rmbinder** [comment]
Category report 3.1.x is not compatible with Admidio version 4.1. You have to use an Admidio version 4.0.x (category report will not be further developed as a plugin. From Admidio 4.1 it is an integral part of Admidio as a module).

**Comment by luebbe** [comment]
ok, thank you. It wasn't clear to me that Kategoriereport isn't compatible
